services:
  api-server:
    image: "ghcr.io/open-rmf/rmf_deployment_template/rmf-deployment/api-server:latest"
    environment:
      RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
    network_mode: "host"

  web-dashboard:
    image: "ghcr.io/open-rmf/rmf_deployment_template/rmf-deployment/dashboard-no-auth:latest"
    environment:
      RMF_SERVER_URL: "http://localhost:8000"
      TRAJECTORY_SERVER_URL: "ws://localhost:8006"
    ports:
      - "3000:80"