amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: base_link
    global_frame_id: map
    odom_frame_id: odom
    scan_topic: scan
    map_topic: map
    alpha1: 0.01 #    Expected process noise in odometry’s rotation estimate from rotation.
    alpha2: 0.01 #    Expected process noise in odometry’s rotation estimate from translation.   
    alpha3: 0.01 #    Expected process noise in odometry’s translation estimate from translation.
    alpha4: 0.01 #    Expected process noise in odometry’s translation estimate from rotation.
    alpha5: 0.01 #    For Omni models only: translation noise.
    service_introspection_mode: "disabled" #    The introspection mode for services. Options are “disabled”, “metadata”, “contents”.
    beam_skip_distance: 0.5 #Ignore beams that most particles disagree with in Likelihood field model. Maximum distance to consider skipping for (m).
    beam_skip_error_threshold: 0.9 #    Percentage of beams after not matching map to force full update due to bad convergence.
    beam_skip_threshold: 0.3 #    Percentage of beams required to skip.
    do_beamskip: false #    Whether to do beam skipping in Likelihood field model.
    laser_model_type: likelihood_field #Which model to use, either beam, likelihood_field, or likelihood_field_prob. Same as likelihood_field but incorporates the beamskip feature, if enabled.
    max_beams: 100 #    How many evenly-spaced beams in each scan to be used when updating the filter.
    max_particles: 2000 #    Maximum allowed number of particles.
    min_particles: 500 #    Minimum allowed number of particles.
    robot_model_type: nav2_amcl::DifferentialMotionModel
    tf_broadcast: true #Set this to false to prevent amcl from publishing the transform between the global frame and the odometry frame.
    transform_tolerance: 0.5 #Time with which to post-date the transform that is published, to indicate that this transform is valid into the future.
    lambda_short: 0.1 #    Exponential decay parameter for z_short part of model.
    laser_likelihood_max_dist: 2.0 #    Maximum distance to do obstacle inflation on map, for use in likelihood_field model.
    laser_max_range: 100.0 #    Maximum scan range to be considered, -1.0 will cause the laser’s reported maximum range to be used.
    laser_min_range: -1.0 #    Minimum scan range to be considered, -1.0 will cause the laser’s reported minimum range to be used.
    pf_err: 0.05 #    Particle Filter population error.
    pf_z: 0.99 #    Particle filter population density. 2.33 is the 99% percentile.
    recovery_alpha_fast: 0.0 #    Exponential decay rate for the fast average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.1.
    recovery_alpha_slow: 0.0 #    Exponential decay rate for the slow average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.001.
    resample_interval: 1 #    Number of filter updates required before resampling.
    save_pose_rate: 0.5 #
    z_hit: 0.9 #    Mixture weight for z_hit part of model, sum of all used z weight must be 1. Beam uses all 4, likelihood model uses z_hi    Maximum rate (Hz) at which to store the last estimated pose and covariance to the parameter server, in the variables ~initial_pose_* and ~initial_cov_*. This saved pose will be used on subsequent runs to initialize the filter (-1.0 to disable).
    sigma_hit: 0.2 #    Standard deviation for Gaussian model used in z_hit part of the model.
    update_min_a: 0.2 #    Rotational movement required before performing a filter update.
    update_min_d: 0.25 #    Translational movement required before performing a filter update.
    z_hit: 0.9 #    Mixture weight for z_hit part of model, sum of all used z weight must be 1. Beam uses all 4, likelihood model uses z_hit and z_rand..
    z_max: 0.05 #    Mixture weight for z_max part of model, sum of all used z weight must be 1. Beam uses all 4, likelihood model uses z_hit and z_rand.
    z_rand: 0.1 #    Mixture weight for z_rand part of model, sum of all used z weight must be 1. Beam uses all 4, likelihood model uses z_hit and z_rand..
    z_short: 0.05 #    Mixture weight for z_short part of model, sum of all used z weight must be 1. Beam uses all 4, likelihood model uses z_hit and z_rand.
    always_reset_initial_pose: false #    Requires that AMCL is provided an initial pose either via topic or initial_pose* parameter (with parameter set_initial_pose: true) when reset. Otherwise, by default AMCL will use the last known pose to initialize.
    first_map_only: false #    Allows AMCL to accept maps more than once on the map_topic. This is especially useful when you’re using the LoadMap service in map_server. Prior to Humble, this is first_map_only_.
    set_initial_pose: True
    initial_pose:
      # used in gazebo
      # x: 5.13584
      # y: 22.9718
      # z: 1.101
      # yaw: -0.0649066 
      # used for testing ekf with rosbag
      x : 5.367
      y : 22.371
      yaw: 1.1
    



map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/root/ff_ws/src/myTesiCode/maps/map-elettra/amcl/map.yaml"
