services:
  api-server:
    image: ghcr.io/open-rmf/rmf-web/api-server:latest
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  dashboard:
    image: ghcr.io/open-rmf/rmf-web/demo-dashboard:latest
    network_mode: "host"
    environment:
      - RMF_SERVER_URL=http://localhost:8000
      - TRAJECTORY_SERVER_URL=ws://localhost:8006