# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "minis"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
  # actions: ["some_action_here"]
  finishing_request: "nothing" # [park, charge, nothing]
  responsive_wait: True # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  robots:
    mini1:
      charger: "dispensa_charge"
      responsive_wait: False # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting.
      # For Nav2RobotAdapter
      navigation_stack: 2
      # tf_mapping_base : base_link
      # tf_mapping_map : map
      init_timeout_sec: 5
      map_frame: "map"
      robot_frame: "base_link"
      initial_map: "L1"
      maps:
        L1:
          map_url: "/root/ff_ws/src/myTesiCode/maps/map-elettra/amcl/map.yaml"
      # initial_pose: [-1.6000019311904907, -0.5031192898750305, 0]

  robot_state_update_frequency: 10.0 # Hz


# fleet_manager:
#   prefix: "http://127.0.0.1:8080"
#   user: "some_user"
#   password: "some_password"

# TRANSFORM CONFIG =============================================================
# For computing transforms between Robot and RMF coordinate systems

# Optional
reference_coordinates:
  L1:
    rmf: [[73.5818, -86.1411],
          [68.1894, -89.2635],
          [61.5902, -100.1195]]
    robot: [[5.181, 22.613],
          [1.726, 20.227],
          [-3.025, 12.522]]
