amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.3
    alpha2: 0.2
    alpha3: 0.1
    alpha4: 0.2
    base_frame_id: base_link
    global_frame_id: map
    laser_model_type: likelihood_field
    odom_frame_id: odom
    max_beams: 100
    max_particles: 2000
    min_particles: 500
    robot_model_type: nav2_amcl::DifferentialMotionModel
    tf_broadcast: true
    transform_tolerance: 0.5
    z_hit: 0.9
    z_max: 0.05
    z_rand: 0.1
    z_short: 0.05
    scan_topic: scan
    set_initial_pose: True
    initial_pose:
      x: 2.920
      y: 18.643
      z: 1.101
      yaw: 1.1
    # yaml_filename: "/home/mini/navros/src/myTesiCode/maps/map-elettra/amcl/map.yaml"
    # map: "/home/mini/navros/src/myTesiCode/maps/map-elettra/amcl/map.yaml"

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "/home/mini/navros/src/myTesiCode/maps/map-elettra/amcl/map.yaml"


# amcl:
#   ros__parameters:
#     use_sim_time: True
#     alpha1: 0.2
#     alpha2: 0.2
#     alpha3: 0.2
#     alpha4: 0.2
#     alpha5: 0.2
#     base_frame_id: "base_link"
#     beam_skip_distance: 0.5
#     beam_skip_error_threshold: 0.9
#     beam_skip_threshold: 0.3
#     do_beamskip: false
#     global_frame_id: "map"
#     lambda_short: 0.1
#     laser_likelihood_max_dist: 2.0
#     laser_max_range: 100.0
#     laser_min_range: -1.0
#     laser_model_type: "likelihood_field"
#     max_beams: 60
#     max_particles: 2000
#     min_particles: 500
#     odom_frame_id: "odom"
#     pf_err: 0.05
#     pf_z: 0.99
#     recovery_alpha_fast: 0.0
#     recovery_alpha_slow: 0.0
#     resample_interval: 1
#     robot_model_type: "nav2_amcl::DifferentialMotionModel"
#     save_pose_rate: 0.5
#     sigma_hit: 0.2
#     tf_broadcast: true
#     transform_tolerance: 1.0
#     update_min_a: 0.2
#     update_min_d: 0.25
#     z_hit: 0.5
#     z_max: 0.05
#     z_rand: 0.5
#     z_short: 0.05
#     scan_topic: scan


# amcl:
#   ros__parameters:
#     use_sim_time: True
#     alpha1: 0.3
#     alpha2: 0.3
#     alpha3: 0.3
#     alpha4: 0.3
#     alpha5: 0.3
#     always_reset_initial_pose: false
#     base_frame_id: base_link
#     beam_skip_distance: 0.5
#     beam_skip_error_threshold: 0.9
#     beam_skip_threshold: 0.3
#     do_beamskip: true
#     first_map_only: true
#     global_frame_id: map
#     initial_pose:
#       x: 0.0
#       y: 0.0
#       yaw: 0.0
#       z: 0.0
#     lambda_short: 0.1
#     laser_likelihood_max_dist: 4.0
#     laser_max_range: 100.0
#     laser_min_range: -1.0
#     laser_model_type: beam
#     map_topic: map
#     max_beams: 60
#     max_particles: 2000
#     min_particles: 500
#     odom_frame_id: odom
#     pf_err: 0.05
#     pf_z: 0.99
#     qos_overrides:
#       /tf:
#         publisher:
#           depth: 100
#           durability: volatile
#           history: keep_last
#           reliability: reliable
#     recovery_alpha_fast: 0.0
#     recovery_alpha_slow: 0.0
#     resample_interval: 1
#     robot_model_type: nav2_amcl::DifferentialMotionModel
#     save_pose_rate: 0.2
#     scan_topic: scan
#     set_initial_pose: false
#     sigma_hit: 0.1
#     tf_broadcast: false
#     transform_tolerance: 1.2
#     update_min_a: 0.2
#     update_min_d: 0.25
#     use_sim_time: True
#     z_hit: 1.2
#     z_max: 0.05
#     z_rand: 0.5
#     z_short: 0.05



